/**
 * Backend error codes — mirrors backend pkg/errors/error.go
 */

export const ErrorCodes = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_DUPLICATE_PHONE: 'AUTH_DUPLICATE_PHONE',
  AUTH_DUPLICATE_USERNAME: 'AUTH_DUPLICATE_USERNAME',

  // Brand
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_DISABLED: 'BRAND_DISABLED',
  BRAND_NOT_ACTIVE: 'BRAND_NOT_ACTIVE',
  BRAND_CODE_DUPLICATED: 'BRAND_CODE_DUPLICATED',

  // Onboarding
  STEP_NOT_SKIPPABLE: 'STEP_NOT_SKIPPABLE',
  INVALID_STEP_KEY: 'INVALID_STEP_KEY',
  ONBOARDING_NOT_READY: 'ONBOARDING_NOT_READY',

  // Location
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  LOCATION_IN_USE: 'LOCATION_IN_USE',
  LOCATION_NAME_DUPLICATED: 'LOCATION_NAME_DUPLICATED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  SUBSCRIPTION_RESTRICTED: 'SUBSCRIPTION_RESTRICTED',
  INVALID_PARAM: 'INVALID_PARAM',

  // Staff (Batch 5)
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  STAFF_PHONE_DUPLICATED: 'STAFF_PHONE_DUPLICATED',
  OWNER_PROTECTED: 'OWNER_PROTECTED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  LOCATION_ASSIGNMENT_INVALID: 'LOCATION_ASSIGNMENT_INVALID',
  INSTRUCTOR_PROFILE_NOT_FOUND: 'INSTRUCTOR_PROFILE_NOT_FOUND',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DUPLICATE_PHONE: 'USER_DUPLICATE_PHONE',

  // Course
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',

  // Course Category / Template / Session (Batch 11)
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_NAME_DUPLICATED: 'CATEGORY_NAME_DUPLICATED',
  COURSE_NOT_ACTIVE: 'COURSE_NOT_ACTIVE',
  COURSE_IN_USE: 'COURSE_IN_USE',
  COURSE_LOCATION_UNAVAILABLE: 'COURSE_LOCATION_UNAVAILABLE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_TIME_INVALID: 'SESSION_TIME_INVALID',
  SESSION_INSTRUCTOR_CONFLICT: 'SESSION_INSTRUCTOR_CONFLICT',
  SESSION_CANCEL_NOT_ALLOWED: 'SESSION_CANCEL_NOT_ALLOWED',
  INSTRUCTOR_NOT_SCHEDULABLE: 'INSTRUCTOR_NOT_SCHEDULABLE',

  // Location Resource (Batch 12a)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_NAME_DUPLICATED: 'RESOURCE_NAME_DUPLICATED',
  RESOURCE_IN_USE: 'RESOURCE_IN_USE',
  RESOURCE_NOT_AVAILABLE: 'RESOURCE_NOT_AVAILABLE',
  SESSION_RESOURCE_CONFLICT: 'SESSION_RESOURCE_CONFLICT',

  // Recurring Schedule (Batch 12b)
  RECURRING_NOT_FOUND: 'RECURRING_NOT_FOUND',
  RECURRING_ALL_CONFLICT: 'RECURRING_ALL_CONFLICT',
  RECURRING_CANCEL_NOT_ALLOWED: 'RECURRING_CANCEL_NOT_ALLOWED',

  // Learner profiles & tags (Batch 13a)
  LEARNER_NOT_FOUND: 'LEARNER_NOT_FOUND',
  LEARNER_ALREADY_EXISTS: 'LEARNER_ALREADY_EXISTS',
  LEARNER_NO_DUPLICATED: 'LEARNER_NO_DUPLICATED',
  LEARNER_IN_USE: 'LEARNER_IN_USE',
  LEARNER_TAG_NOT_FOUND: 'LEARNER_TAG_NOT_FOUND',
  LEARNER_TAG_NAME_DUPLICATED: 'LEARNER_TAG_NAME_DUPLICATED',

  // Entitlement products & grants (Batch 13b)
  ENTITLEMENT_PRODUCT_NOT_FOUND: 'ENTITLEMENT_PRODUCT_NOT_FOUND',
  ENTITLEMENT_PRODUCT_NAME_DUPLICATED: 'ENTITLEMENT_PRODUCT_NAME_DUPLICATED',
  ENTITLEMENT_PRODUCT_INACTIVE: 'ENTITLEMENT_PRODUCT_INACTIVE',
  ENTITLEMENT_SCOPE_INVALID: 'ENTITLEMENT_SCOPE_INVALID',
  ENTITLEMENT_NOT_FOUND: 'ENTITLEMENT_NOT_FOUND',
  ENTITLEMENT_INSUFFICIENT: 'ENTITLEMENT_INSUFFICIENT',
  ENTITLEMENT_NOT_ADJUSTABLE: 'ENTITLEMENT_NOT_ADJUSTABLE',

  // Booking (Batch 13c)
  SESSION_NOT_BOOKABLE: 'SESSION_NOT_BOOKABLE',
  BOOKING_WINDOW_CLOSED: 'BOOKING_WINDOW_CLOSED',
  SESSION_FULL: 'SESSION_FULL',
  BOOKING_DUPLICATE: 'BOOKING_DUPLICATE',
  LEARNER_NOT_BOOKABLE: 'LEARNER_NOT_BOOKABLE',
  ENTITLEMENT_NONE_AVAILABLE: 'ENTITLEMENT_NONE_AVAILABLE',
  ENTITLEMENT_NOT_USABLE: 'ENTITLEMENT_NOT_USABLE',
  ENTITLEMENT_SCOPE_MISMATCH: 'ENTITLEMENT_SCOPE_MISMATCH',
  BOOKING_FREQUENCY_EXCEEDED: 'BOOKING_FREQUENCY_EXCEEDED',
  ASSISTED_REASON_REQUIRED: 'ASSISTED_REASON_REQUIRED',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
  BOOKING_CANCEL_NOT_ALLOWED: 'BOOKING_CANCEL_NOT_ALLOWED',
  BOOKING_CANCEL_DEADLINE_PASSED: 'BOOKING_CANCEL_DEADLINE_PASSED',

  // Waitlist (Batch 13d)
  WAITLIST_NOT_ALLOWED: 'WAITLIST_NOT_ALLOWED',
  WAITLIST_SESSION_NOT_FULL: 'WAITLIST_SESSION_NOT_FULL',
  WAITLIST_FULL: 'WAITLIST_FULL',
  WAITLIST_DUPLICATE: 'WAITLIST_DUPLICATE',
  WAITLIST_ENTRY_NOT_FOUND: 'WAITLIST_ENTRY_NOT_FOUND',
  WAITLIST_NOT_PROMOTABLE: 'WAITLIST_NOT_PROMOTABLE',

  // 签到 / 履约 / 爽约 (Batch 13e)
  ATTENDANCE_ALREADY_MARKED: 'ATTENDANCE_ALREADY_MARKED',
  BOOKING_NOT_ATTENDABLE: 'BOOKING_NOT_ATTENDABLE',
  SESSION_NOT_ENDABLE: 'SESSION_NOT_ENDABLE',
  BOOKING_NOT_CONFIRMABLE: 'BOOKING_NOT_CONFIRMABLE',

  // Training
  TRAINING_NOT_FOUND: 'TRAINING_NOT_FOUND',

  // RBAC (Batch 6)
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Custom Roles (Batch 7)
  ROLE_IS_SYSTEM: 'ROLE_IS_SYSTEM',
  ROLE_IN_USE: 'ROLE_IN_USE',
  ROLE_PERMISSION_EXCEEDS_ACTOR: 'ROLE_PERMISSION_EXCEEDS_ACTOR',
  ROLE_CODE_DUPLICATED: 'ROLE_CODE_DUPLICATED',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

/**
 * Backend API response shape
 */
export interface ApiResponse<T = unknown> {
  code: string | null
  message: string
  data: T
}

export interface ApiError {
  code: string
  message: string
  httpStatus: number
}

/**
 * Custom API error class
 *
 * `data` carries the optional structured payload backend may return alongside an
 * error code — e.g. QUOTA_EXCEEDED includes `{current, max}` so the frontend can
 * render quota counters inline rather than a static "请升级套餐" message.
 */
export class ApiErrorClass extends Error {
  code: string
  httpStatus: number
  data: unknown

  constructor(code: string, message: string, httpStatus: number, data: unknown = null) {
    super(message)
    this.name = 'ApiError'
    this.code = code
    this.httpStatus = httpStatus
    this.data = data
  }
}

/**
 * Shape returned by backend for QUOTA_EXCEEDED errors (Batch 4+).
 */
export interface QuotaExceededDetails {
  current: number
  max: number
}

/**
 * Narrow helper: pulls `{current, max}` off an ApiError when its code is QUOTA_EXCEEDED.
 * Returns null if shape doesn't match — keeps render code safe even if backend changes.
 */
export function getQuotaDetails(err: unknown): QuotaExceededDetails | null {
  if (!(err instanceof ApiErrorClass)) return null
  if (err.code !== ErrorCodes.QUOTA_EXCEEDED) return null
  const data = err.data
  if (
    data &&
    typeof data === 'object' &&
    'current' in data &&
    'max' in data &&
    typeof (data as { current: unknown }).current === 'number' &&
    typeof (data as { max: unknown }).max === 'number'
  ) {
    return data as QuotaExceededDetails
  }
  return null
}
